server.port=${PORT:8080}

gemini.api.key=${GEMINI_API_KEY:}

youtube.api.key=${YOUTUBE_API_KEY:}

spring.data.mongodb.uri=${MONGO_URI:}

auth0.audience=${AUTH0_AUDIENCE:}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER:}

spring.jackson.deserialization.fail-on-unknown-properties=false
